### ISSUE TITLE
note: optimistic parsing in ASN1

### ISSUE THREAD

**Issue by coolaj86** [mylofi/webauthn-local-client#14]
Just so you know, I used an optimistic approach to the ASN1 parsing, which is why that library is only 5kb instead of 100kb.

In short this means that it is very rare (but known to be possible) for ***certificate*** PEMs to throw false negative errors.

I _think_ it's impossible to happen for a ***keypair*** PEM - because it won't have arbitrary nested data, user-selected data, or unknown optional metadata fields.

So I'd love to know about it and get a copy of the keypair if you ever get an error when parsing an OS keypair, but simply deleting it and grabbing a new one is the workaround.

More here: https://github.com/therootcompany/asn1.js/issues/4

**Comment by getify** [comment]
thanks for the info, could end up being really useful in future debugging! :)

**Comment by getify** [comment]
closing for now, but we may need to revisit. good to have this info here for posterity.
